# -*- coding: utf-8 -*-
"""
  compliance_comp_base.py generated by WhatsOpt 1.8.2
"""
# DO NOT EDIT unless you know what you are doing
# whatsopt_url:
# analysis_id: 6


import numpy as np
from numpy import nan
from os import path
from importlib import import_module
from openmdao.api import ExplicitComponent


class ComplianceCompBase(ExplicitComponent):
    """An OpenMDAO base component to encapsulate ComplianceComp discipline"""

    def setup(self):
        self.add_input("displacements_0", val=np.ones((102,)), desc="")
        self.add_input("displacements_1", val=np.ones((102,)), desc="")

        self.add_output("compliance_0", val=np.ones((1,)), desc="")

        self.add_output("compliance_1", val=np.ones((1,)), desc="")
