# -*- coding: utf-8 -*-
"""
  displacements_comp_base.py generated by WhatsOpt 1.8.2
"""
# DO NOT EDIT unless you know what you are doing
# whatsopt_url:
# analysis_id: 6


import numpy as np
from numpy import nan
from os import path
from importlib import import_module
from openmdao.api import ExplicitComponent


class DisplacementsCompBase(ExplicitComponent):
    """An OpenMDAO base component to encapsulate DisplacementsComp discipline"""

    def setup(self):
        self.add_input("d_0", val=np.ones((104,)), desc="")
        self.add_input("d_1", val=np.ones((104,)), desc="")

        self.add_output("displacements_0", val=np.ones((102,)), desc="")

        self.add_output("displacements_1", val=np.ones((102,)), desc="")
