# -*- coding: utf-8 -*-
"""
  disc1_base.py generated by WhatsOpt 1.7.0
"""
# DO NOT EDIT unless you know what you are doing
# whatsopt_url: http://192.168.99.100:3000
# analysis_id: 34


# import numpy as np
from os import path
from importlib import import_module
from openmdao.api import ExplicitComponent


class Disc1Base(ExplicitComponent):
    """An OpenMDAO base component to encapsulate Disc1 discipline"""

    def setup(self):
        self.add_input("x", val=2, desc="")
        self.add_input("y2", val=1.0, desc="")
        self.add_input("z", val=[5, 2], desc="")

        self.add_output("y1", val=1.0, desc="")
