# -*- coding: utf-8 -*-
"""
  interp_base.py generated by WhatsOpt 1.8.2
"""
# DO NOT EDIT unless you know what you are doing
# whatsopt_url: https://ether.onera.fr/whatsopt
# analysis_id: 4


import numpy as np
from numpy import nan
from os import path
from importlib import import_module
from openmdao.api import ExplicitComponent


class InterpBase(ExplicitComponent):
    """An OpenMDAO base component to encapsulate Interp discipline"""

    def setup(self):
        self.add_input("h_cp", val=[1.0, 1.0, 1.0, 1.0, 1.0], desc="")

        self.add_output("h", val=np.ones((1, 50)), desc="")
