# -*- coding: utf-8 -*-
"""
  local_stiffness_matrix_comp.py generated by WhatsOpt 1.8.2
"""
import numpy as np
from local_stiffness_matrix_comp_base import LocalStiffnessMatrixCompBase


class LocalStiffnessMatrixComp(LocalStiffnessMatrixCompBase):
    """An OpenMDAO component to encapsulate LocalStiffnessMatrixComp discipline"""

    def compute(self, inputs, outputs):
        """LocalStiffnessMatrixComp computation"""
        if self._impl:
            # Docking mechanism: use implementation if referenced in .whatsopt_dock.yml file
            self._impl.compute(inputs, outputs)
        else:
            outputs["K_local"] = np.ones((50, 4, 4))


# Reminder: inputs of compute()
#
#       inputs['I'] -> shape: (50,), type: Float

# To declare partial derivatives computation ...
#
#    def setup(self):
#        super(LocalStiffnessMatrixComp, self).setup()
#        self.declare_partials('*', '*')
#
#    def compute_partials(self, inputs, partials):
#        """ Jacobian for LocalStiffnessMatrixComp """
#
#       	partials['K_local', 'I'] = np.zeros((800, 50))
