# -*- coding: utf-8 -*-
"""
  local_stiffness_matrix_comp_base.py generated by WhatsOpt 1.8.2
"""
# DO NOT EDIT unless you know what you are doing
# whatsopt_url: https://ether.onera.fr/whatsopt
# analysis_id: 4


import numpy as np
from numpy import nan
from os import path
from importlib import import_module
from openmdao.api import ExplicitComponent


class LocalStiffnessMatrixCompBase(ExplicitComponent):
    """An OpenMDAO base component to encapsulate LocalStiffnessMatrixComp discipline"""

    def setup(self):
        self.add_input("I", val=np.ones((50,)), desc="")

        self.add_output("K_local", val=np.ones((50, 4, 4)), desc="")
