# -*- coding: utf-8 -*-
"""
  obj_sum_base.py generated by WhatsOpt 1.8.2
"""
# DO NOT EDIT unless you know what you are doing
# whatsopt_url: https://ether.onera.fr/whatsopt
# analysis_id: 4


import numpy as np
from numpy import nan
from os import path
from importlib import import_module
from openmdao.api import ExplicitComponent


class ObjSumBase(ExplicitComponent):
    """An OpenMDAO base component to encapsulate ObjSum discipline"""

    def setup(self):
        self.add_input("compliance_0", val=np.ones((1,)), desc="")
        self.add_input("compliance_1", val=np.ones((1,)), desc="")

        self.add_output("obj", val=np.ones((1,)), desc="")
